[package]
name = "src-redteam-001"
version = "0.1.0"
edition = "2024"

[dependencies]
comfy-table = "7.2.1"
pnet = "0.35.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
